#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#include "instructions.h"
#include "implementations.h"

#ifdef __clang__
// Diagnostic management for Clang -- we turn off mostly uninteresting
// stuff related to the weird array initialisation tricks done here.
# pragma clang diagnostic push
//     "warning: use of GNU array range extension"
# pragma clang diagnostic ignored "-Wgnu-designator"
//     "warning: subobject initialization overrides initialization of
//     other fields within its enclosing subobject"
# pragma clang diagnostic ignored "-Winitializer-overrides"
#endif

// NOTE: This whole thing would be better as OOP
    // TODO: implement in c++...
        //TODO: learn c++

/**
    0  - literal bit zero
    1  - literal bit one
    *  - filed that has been used as a lookup key
    X  - immediate, print hex
    I  - immediate, print dec
    C  - code, field can be read by error handler for addition info
        - non-printing, except SDBBP (unimplemented)
        - example SYSCALL
    BO - offset(base)
        B - base register
        O - offset immediate, print dec
    [Other Uppercase] - register field (Number given is the N in $N)
    [Other lowercase] - optional register field (Number given is the N in $N)
                        - If N == value given in default_reg don't show register
                            - Example JALR
                        - support for multiple optional fields are unimplemented and not used
 */

enum movci_instructions {
    MOVF,
    MOVT,
};

static const instruction_info movci_instruction_map[] = {
    [MOVF] = { "movf",
               false, NULL,  0x0,
               "******SSSSSCCC0*DDDDD00000******",
               "DSC", 0,
               NULL},
    [MOVT] = { "movt",
               false, NULL,  0x0,
               "******SSSSSCCC0*DDDDD00000******",
               "DSC", 0,
               NULL},
};

enum srl_instructions {
    ___SRL,
    ROTR,
};

static const instruction_info srl_instruction_map[] = {
    [___SRL]  = { "srl",
                  false, NULL,  0x0,
                  "******0000*TTTTTDDDDDUUUUU******",
                  "DTU", 0,
                  implementation_SRL},
    [ROTR]    = { "rotr",
                  false, NULL,  0x0,
                  "******0000*TTTTTDDDDDUUUUU******",
                  "DTU", 0,
                  NULL},
};

enum srlv_instructions {
    ___SRLV,
    ROTRV,
};

static const instruction_info srlv_instruction_map[] = {
    [___SRLV]  = { "srlv",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTDDDDD0000*******",
                   "DTS", 0,
                   implementation_SRLV},
    [ROTRV]    = { "rotrv",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTDDDDD0000*******",
                   "DTS", 0,
                   NULL},
};

enum meta_meta_meta_null_instructions {
    _____NOP   = 0x00,
    _____SSNOP = 0x01,
    _____EHB   = 0x03,
    _____PAUSE = 0x05,
};

static const instruction_info meta_meta_meta_null_instruction_map[] = {
    [0 ... 31]   = { "sll",
                     false, NULL, 0x0,
                     "******00000TTTTTDDDDDUUUUU******",
                     "DTU", 0,
                     implementation_SLL},
    [_____NOP]   = { "nop",
                     false, NULL, 0x0,
                     "******00000*********************",
                     "", 0,
                     NULL},
    [_____SSNOP] = { "ssnop",
                     false, NULL, 0x0,
                     "******00000*********************",
                     "", 0,
                     NULL},
    [_____EHB]   = { "ehb",
                     false, NULL, 0x0,
                     "******00000*********************",
                     "", 0,
                     NULL},
    [_____PAUSE] = { "pause",
                     false, NULL, 0x0,
                     "******00000*********************",
                     "", 0,
                     NULL},
};

enum meta_meta_null_instructions {
    ____NOP   = 0x0000,
    ____SSNOP = 0x0000,
    ____EHB   = 0x0000,
    ____PAUSE = 0x0000,
};

static const instruction_info meta_meta_null_instruction_map[] = {
        [0 ... 31]  = { "sll",
                        false, NULL, 0x0,
                        "******00000TTTTTDDDDDUUUUU******",
                        "DTU", 0,
                        implementation_SLL},
        [____NOP]   = { "SLL",
                        true, meta_meta_meta_null_instruction_map, 0x000007C0,
                        "",
                        "", 0,
                        NULL},
};

enum meta_null_instructions {
    ___NOP   = 0x0000,
    ___SSNOP = 0x0000,
    ___EHB   = 0x0000,
    ___PAUSE = 0x0000,
};

static const instruction_info meta_null_instruction_map[] = {
        [0 ... 31] = { "sll",
                       false, NULL, 0x0,
                       "******00000TTTTTDDDDDUUUUU******",
                       "DTU", 0,
                       implementation_SLL},
        [___NOP]   = { "SLL",
                       true, meta_meta_null_instruction_map, 0x0000F800,
                       "",
                       "", 0,
                       NULL},
};

// To mimic the layout in the architecture reference ---
// clang-format off
enum special_instructions {
    NOP = 0, SSNOP = 0, EHB = 0, PAUSE = 0,

    SLL = 0,   MOVCI, SRL,       SRA,  SLLV,    LSA,   SRLV,     SRAV,
    JR,        JALR,  MOVZ,      MOVN, SYSCALL, BREAK,           SYNC = 15,
    MFHI,      MTHI,  MFLO,      MTLO,
    MULT = 24, MULTU, DIV,       DIVU,
    ADD = 32,  ADDU,  SUB,       SUBU, AND,     OR,    XOR,      NOR,
    SLT = 42,  SLTU,
    TGE = 48,  TGEU,  TLT,       TLTU, TEQ,            TNE = 54,
};
// clang-format on

static const instruction_info special_instruction_map[] = {
    [SLL]     = { "SLL", // THIS IS A REAL BIG FUCKER
                  true, meta_null_instruction_map, 0x001F0000,
                  "",
                  "", 0,
                  NULL},
    [MOVCI]   = { "MOVCI",
                  true, movci_instruction_map, 0x00010000,
                  "",
                  "", 0,
                  NULL},
    [SRL]     = { "SRL",
                  true, srl_instruction_map, 0x00200000,
                  "",
                  "", 0,
                  NULL},
    [SRA]     = { "sra",
                  false, NULL,  0x0,
                  "******00000TTTTTDDDDDAAAAA******",
                  "DTA", 0,
                  NULL},
    [SLLV]    = { "sllv",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DTS", 0,
                  implementation_SLLV},
    [LSA]     = { "lsa", false, NULL,  0x0,
                  "******CCCCCCCCCCCCCCCCCCCC******",
                  "", 0,
                  NULL},
    [SRLV]    = { "SRLV",
                  true, srlv_instruction_map, 0x00000040,
                  "",
                  "", 0,
                  NULL},
    [SRAV]    = { "srav",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DTS", 0,
                  NULL},
    [JR]      = { "jr",
                  false, NULL, 0x0,
                  "******SSSSS0000000000AAAAA******",
                  "S", 0,
                  implementation_JR},
    [JALR]    = { "jalr",
                  false, NULL, 0x0,
                  "******SSSSS00000DDDDDAAAAA******",
                  "dS", 31,
                  NULL},
    [MOVZ]    = { "movz",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  NULL},
    [MOVN]    = { "movn",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  NULL},
    [SYSCALL] = { "syscall",
                  false, NULL,  0x0,
                  "******CCCCCCCCCCCCCCCCCCCC******",
                  "", 0,
                  implementation_SYSCALL},
    [BREAK]   = { "break",
                  false, NULL,  0x0,
                  "******CCCCCCCCCCCCCCCCCCCC******",
                  "", 0,
                  NULL},
    [SYNC]    = { "sync",
                  false, NULL, 0x0,
                  "******000000000000000AAAAA******",
                  "a", 0,
                  NULL},
    [MFHI]    = { "mfhi",
                  false, NULL, 0x0,
                  "******0000000000DDDDD00000******",
                  "D", 0,
                  NULL/*implementation_MFHI*/},
    [MTHI]    = { "mthi",
                  false, NULL, 0x0,
                  "******SSSSS000000000000000******",
                  "S", 0,
                  NULL/*implementation_MTHI*/},
    [MFLO]    = { "mflo",
                  false, NULL, 0x0,
                  "******0000000000DDDDD00000******",
                  "D", 0,
                  NULL/*implementation_MFLO*/},
    [MTLO]    = { "mtlo",
                  false, NULL, 0x0,
                  "******SSSSS000000000000000******",
                  "S", 0,
                  NULL/*implementation_MTLO*/},
    [MULT]    = { "mult",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL/*implementation_MULT*/},
    [MULTU]   = { "multu",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL/*implementation_MULTU*/},
    [DIV]     = { "div",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL/*implementation_DIV*/},
    [DIVU]    = { "divu",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL/*implementation_DIVU*/},
    [ADD]     = { "add",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  implementation_ADD},
    [ADDU]    = { "addu",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  NULL/*implementation_ADDU*/},
    [SUB]     = { "sub",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  implementation_SUB},
    [SUBU]    = { "subu",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  NULL/*implementation_SUBU*/},
    [AND]     = { "and",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  implementation_AND},
    [OR]      = { "or",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  implementation_OR},
    [XOR]     = { "xor",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  implementation_XOR},
    [NOR]     = { "nor",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  NULL},
    [SLT]     = { "slt",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  implementation_SLT},
    [SLTU]    = { "sltu",
                  false, NULL,  0x0,
                  "******SSSSSTTTTTDDDDD00000******",
                  "DST", 0,
                  NULL/*implementation_SLTU*/},
    [TGE]     = { "tge",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL},
    [TGEU]    = { "tgeu",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL},
    [TLT]     = { "tlt",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL},
    [TLTU]    = { "tltu",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL},
    [TEQ]     = { "teq",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL},
    [TNE]     = { "tne",
                  false, NULL,  0x0,
                  "******SSSSSTTTTT0000000000******",
                  "ST", 0,
                  NULL},
};

// To mimic the layout in the architecture reference ---
// clang-format off
enum special2_instructions {
    MADD,     MADDU, MUL,    MSUB = 4, MSUBU,



    CLZ = 32, CLO,


    SDBBP = 63,
};
// clang-format on

static const instruction_info special2_instruction_map[] = {
    [MADD]  = { "madd",
                false, NULL, 0x0,
                "******SSSSSTTTTT0000000000******",
                "ST", 0,
                NULL},
    [MADDU] = { "maddu",
                false, NULL, 0x0,
                "******SSSSSTTTTT0000000000******",
                "ST", 0,
                NULL},
    [MUL]   = { "mul",
                false, NULL,  0x0,
                "******SSSSSTTTTTDDDDD00000******",
                "DST", 0,
                implementation_MUL},
    [MSUB]  = { "msub",
                false, NULL, 0x0,
                "******SSSSSTTTTT0000000000******",
                "ST", 0,
                NULL},
    [MSUBU] = { "msubu",
                false, NULL, 0x0,
                "******SSSSSTTTTT0000000000******",
                "ST", 0,
                NULL},
    [CLZ]   = { "clz", // FIXME: contradictory spec
                false, NULL, 0x0,
                "******SSSSSTTTTTDDDDD00000******",
                "DS", 0,
                NULL},
    [CLO]   = { "clo", // FIXME: contradictory spec
                false, NULL, 0x0,
                "******SSSSSTTTTTDDDDD00000******",
                "DS", 0,
                NULL},
    [SDBBP] = { "sdbbp",
                false, NULL,  0x0,
                "******CCCCCCCCCCCCCCCCCCCC******",
                "C", 0,
                NULL},
};

enum bshfl_instructions {
    WSBH = 3,

    SEB = 16,
    SEH = 24,
};

static const instruction_info bshfl_instruction_map[] = {
    [WSBH] = { "wsbh",
               false, NULL, 0x0,
               "******00000TTTTTDDDDD***********",
               "DT", 0,
               NULL},
    [SEB]  = { "seb",
               false, NULL, 0x0,
               "******00000TTTTTDDDDD***********",
               "DT", 0,
               NULL},
    [SEH]  = { "seh",
               false, NULL, 0x0,
               "******00000TTTTTDDDDD***********",
               "DT", 0,
               NULL},
};

// To mimic the layout in the architecture reference ---
// clang-format off
enum special3_instructions {
    EXT,   INS,


    LWLE = 25, LWRE, CACHEE, SBE,      SHE, SCE, SWE,
    BSHFL,     SWLE,      SWRE, PREFE,
    LBUE = 40, LHUE,                    LBE = 44, LHE, LLE, LWE,

    RDHWR = 59,
};
// clang-format on

static const instruction_info special3_instruction_map[] = {
    [EXT]    = { "ext",
                 false, NULL, 0x0,
                 "******SSSSSTTTTTDDDDDAAAAA******",
                 "TSAD", 0,
                 NULL},
    [INS]    = { "ins",
                 false, NULL, 0x0,
                 "******SSSSSTTTTTDDDDDAAAAA******",
                 "TSAD", 0,
                 NULL},
    [LWLE]   = { "lwle",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [LWRE]   = { "lwre",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [CACHEE] = { "cachee",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [SBE]    = { "sbe",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [SHE]    = { "she",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [SCE]    = { "sce",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [SWE]    = { "swe",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [BSHFL]  = { "BSHFL",
                 true, bshfl_instruction_map, 0x000007C0,
                 "",
                 "", 0,
                 NULL},
    [SWLE]   = { "swle",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [SWRE]   = { "swre",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [PREFE]  = { "prefe",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [LBUE]   = { "lbue",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [LHUE]   = { "lhue",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [LBE]    = { "lbe",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [LHE]    = { "lhe",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [LLE]    = { "lle",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [LWE]    = { "lwe",
                 false, NULL, 0x0,
                 "******BBBBBTTTTTOOOOOOOOO0******",
                 "TO", 0,
                 NULL},
    [RDHWR]  = { "rdhwr",
                 false, NULL, 0x0,
                 "******00000TTTTTDDDDD00000******",
                 "TD", 0,
                 NULL},
};

// To mimic the layout in the architecture reference ---
// clang-format off
enum regimm_instructions {
    BLTZ,        BGEZ,   BLTZL,   BGEZL,
    TGEI = 8,    TGEIU,  TLTI,    TLTIU,   TEQI,      TNEI = 14,
    BLTZAL = 16, BGEZAL, BLTZALL, BGEZALL,
    SYNCI = 31,
};
// clang-format on

static const instruction_info regimm_instruction_map[] = {
    [BLTZ]    = { "bltz",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  implementation_BLTZ},
    [BGEZ]    = { "bgez",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  implementation_BGEZ},
    [BLTZL]   = { "bltzl",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [BGEZL]   = { "bgezl",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [TGEI]    = { "tgei",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [TGEIU]   = { "tgeiu",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [TLTI]    = { "tlti",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [TLTIU]   = { "tltiu",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [TEQI]    = { "teqi",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [TNEI]    = { "tnei",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [BLTZAL]  = { "bltzal",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [BGEZAL]  = { "bgezal",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [BLTZALL] = { "bltzall",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [BGEZALL] = { "bgezall",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "SI", 0,
                  NULL},
    [SYNCI]   = { "synci",
                  false, NULL, 0x0,
                  "******SSSSS*****IIIIIIIIIIIIIIII",
                  "O", 0,
                  NULL},
};

// To mimic the layout in the architecture reference ---
// clang-format off
enum instructions {
    SPECIAL, REGIMM, J,    JAL,   BEQ,           BNE,       BLEZ,     BGTZ,
    ADDI,    ADDIU,  SLTI, SLTIU, ANDI,          ORI,       XORI,     LUI,
    COP0,    COP1,   COP2, COP1X, BEQL,          BNEL,      BLEZL,    BGTZL,
                                  SPECIAL2 = 28, JALX,      MSA,      SPECIAL3,
    LB,      LH,     LWL,  LW,    LBU,           LHU,       LWR,
    SB = 40, SH,     SWL,  SW,                              SWR = 46, CACHE,
    LL,      LWC1,   LWC2, PREF,                 LDC1 = 53, LDC2,
    SC = 56, SWC1,   SWC2,                       SDC1 = 61, SDC2,
};
// clang-format on

const instruction_info instruction_map[] = {
    [SPECIAL]  = { "SPECIAL",
                   true, special_instruction_map, 0x0000003F,
                   "",
                   "", 0,
                   NULL},
    [REGIMM]   = { "REGIMM",
                   true, regimm_instruction_map, 0x001F0000,
                   "",
                   "", 0,
                   NULL},
    [J]        = { "j",
                   false, NULL,  0x0,
                   "******XXXXXXXXXXXXXXXXXXXXXXXXXX",
                   "X", 0,
                   implementation_J},
    [JAL]      = { "jal",
                   false, NULL,  0x0,
                   "******XXXXXXXXXXXXXXXXXXXXXXXXXX",
                   "X", 0,
                   implementation_JAL},
    [BEQ]      = { "beq",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "STI", 0,
                   implementation_BEQ},
    [BNE]      = { "bne",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "STI", 0,
                   implementation_BNE},
    [BLEZ]     = { "blez",
                   false, NULL,  0x0,
                   "******SSSSS00000IIIIIIIIIIIIIIII",
                   "SI", 0,
                   implementation_BLEZ},
    [BGTZ]     = { "bgtz",
                   false, NULL,  0x0,
                   "******SSSSS00000IIIIIIIIIIIIIIII",
                   "SI", 0,
                   implementation_BGTZ},
    [ADDI]     = { "addi",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "TSI", 0,
                   implementation_ADDI},
    [ADDIU]    = { "addiu",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "TSI", 0,
                   NULL/*implementation_ADDIU*/},
    [SLTI]     = { "slti",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "TSI", 0,
                   implementation_SLTI},
    [SLTIU]    = { "sltiu",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "TSI", 0,
                   NULL/*implementation_SLTIU*/},
    [ANDI]     = { "andi",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTUUUUUUUUUUUUUUUU",
                   "TSU", 0,
                   implementation_ANDI},
    [ORI]      = { "ori",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTUUUUUUUUUUUUUUUU",
                   "TSU", 0,
                   implementation_ORI},
    [XORI]     = { "xori",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTUUUUUUUUUUUUUUUU",
                   "TSU", 0,
                   implementation_XORI},
    [LUI]      = { "lui",
                   false, NULL,  0x0,
                   "******00000TTTTTUUUUUUUUUUUUUUUU",
                   "TU", 0,
                   implementation_LUI},
    [COP0]     = { "COP0",
                   true, NULL/*cop0_instruction_map*/, 0x3F,
                   "",
                   "", 0,
                   NULL},
    [COP1]     = { "COP1",
                   true, NULL/*cop1_instruction_map*/, 0x3F,
                   "",
                   "", 0,
                   NULL},
    [COP2]     = { "COP2",
                   true, NULL/*cop2_instruction_map*/, 0x3F,
                   "",
                   "", 0,
                   NULL},
    [COP1X]    = { "COP1X",
                   true, NULL/*cop1X_instruction_map*/, 0x3F,
                   "",
                   "", 0,
                   NULL},
    [BEQL]     = { "beql",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "STI", 0,
                   NULL},
    [BNEL]     = { "bnel",
                   false, NULL,  0x0,
                   "******SSSSSTTTTTIIIIIIIIIIIIIIII",
                   "STI", 0,
                   NULL},
    [BLEZL]    = { "blezl",
                   false, NULL,  0x0,
                   "******SSSSS00000IIIIIIIIIIIIIIII",
                   "SI", 0,
                   NULL},
    [BGTZL]    = { "bgtzl",
                   false, NULL,  0x0,
                   "******SSSSS00000IIIIIIIIIIIIIIII",
                   "SI", 0,
                   NULL},
    [SPECIAL2] = { "SPECIAL2",
                   true, special2_instruction_map, 0x0000003F,
                   "",
                   "", 0,
                   NULL},
    [JALX]     = { "jalx", // FIXME: no spec given
                   false, NULL, 0x0,
                   "",
                   "", 0,
                   NULL},
    [MSA]      = { "MSA",
                   true, NULL/*msa_instruction_map*/, 0x3F,
                   "",
                   "", 0,
                   NULL},
    [SPECIAL3] = { "SPECIAL3",
                   true, special3_instruction_map, 0x0000003F,
                   "",
                   "", 0,
                   NULL},
    [LB]       = { "lb",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   implementation_LB},
    [LH]       = { "lh",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   implementation_LH},
    [LWL]      = { "lwl",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LW]       = { "lw",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   implementation_LW},
    [LBU]      = { "lbu",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LHU]      = { "lhu",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LWR]      = { "lwr",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [SB]       = { "sb",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   implementation_SB},
    [SH]       = { "sh",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   implementation_SH},
    [SWL]      = { "swl",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [SW]       = { "sw",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   implementation_SW},
    [SWR]      = { "swr",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [CACHE]    = { "cache",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LL]       = { "ll",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LWC1]     = { "lwc1",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LWC2]     = { "lwc2",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [PREF]     = { "pref",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LDC1]     = { "ldc1",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [LDC2]     = { "ldc2",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [SC]       = { "sc",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [SWC1]     = { "swc1",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [SWC2]     = { "swc2",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [SDC1]     = { "sdc1",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
    [SDC2]     = { "sdc2",
                   false, NULL,  0x0,
                   "******BBBBBTTTTTOOOOOOOOOOOOOOOO",
                   "TO", 0,
                   NULL},
};

#if 0
// Things get hard to follow past this point
enum cop0_instructions  {};
enum cop1_instructions  {};
enum cop2_instructions  {};
enum cop1x_instructions {};
#endif

#ifdef __clang__
# pragma clang diagnostic pop
#endif
